spring.application.name=trellite

spring.datasource.url=jdbc:postgresql://localhost:5432/trellite
spring.datasource.username=nikola
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
logging.level.org.hibernate=DEBUG