spring.application.name=trellite

spring.datasource.url=jdbc:postgresql://localhost:5432/trellite
spring.datasource.username=nikola
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
logging.level.org.hibernate=DEBUG

spring.mongodb.uri=mongodb://localhost:27017/
spring.mongodb.database=trellite
spring.mongodb.port=27017

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
logging.level.org.example.trellite.boardList.BoardListServiceImpl=INFO
logging.file.name=logs/boardListServiceImpl.log
